# Repository
app_repo_url: https://github.com/Nithin-Rokkam/MERN-PROJECT.git
app_repo_version: main

# Paths & service
app_user: exptracker
app_group: exptracker
deploy_root: /opt/expense-tracker
frontend_dir: "{{ deploy_root }}/client/expense-tracker"
backend_dir: "{{ deploy_root }}/server"
service_name: expense-tracker
backend_port: 8000
public_domain: 65.2.123.158

# Mongo selection
mongo_use_atlas: true
mongo_data_path: /var/lib/mongodb

# TLS / Proxy
enable_ssl: false

